server:
  port: 8001

logging:
  level:
    root: info
  file:
    name: logs/system.log

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comments
    username: root
    password: NEWCASTLE